---
- name: Deploy Docker Image to Container
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: rahulsharma4578/calculator
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: rahulsharma4578
        image: rahulsharma4578/calculator
        state: started
        tty: yes
        interactive: yes

